version: "3.8"
services:
  myapp:
    build: ./
    container_name: pilespacing_c
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    network_mode: host
